### ISSUE TITLE
how is reward defined in Alaska flight booking?

### ISSUE THREAD

**Issue by khliu1238** [stanfordnlp/wge#8]
hi:

I looked into the Alaska flight booking template and didn't see any natural language instructions. How is reward defined in Alaska case? Does it reward whenever the 'find flights' button is clicked with all fields filled out? Any other constraint? I can see no date is included in the constraint (or is much more loosely given, ex: always in March 2017), given the success rate of [choose date] is .52 and Alaska flight booking has .86, not sure if any constraint included.

**Comment by ppasupat** [comment]
Note that the Alaska environment we used in the paper is named "[Alaska-auto](https://github.com/stanfordnlp/wge/tree/master/third-party/miniwob-sandbox/html/flight/Alaska-auto)" in the code. The environment named "Alaska" is a replication of the original task from Shi et al., which is easier than Alaska-auto.

- The goal is provided as key-value pairs.
- The reward is defined in the `validateForm` function in [`wrapper.js`](https://github.com/stanfordnlp/wge/blob/master/third-party/miniwob-sandbox/html/flight/flight-common/wrapper.js#L86). The reward is the fraction of fields that are entered correctly when the "Find Flight" button is clicked. However, the following scenarios will result in an immediate -1 reward:
  - A link that would navigate away from the page 
  - "Find Flight" is clicked when the a required field is not filled. The required fields are defined in the `validateRequiredFields` method [here](https://github.com/stanfordnlp/wge/blob/master/third-party/miniwob-sandbox/html/flight/Alaska-auto/wrapper.html#L89).
- The dates are given in the "Departure Day" and "Returning Day" fields, and are included in the reward. However, the date is restricted to within March 2017. This would explain why choose-date gets a lower success rate -- it requires the agent to pick dates in different months.

**Comment by khliu1238** [comment]
that might not be accurate, as you report sum of partial reward instead of success rate in Alaska ticking booking, which probably would be much lower if a success is considered correct input of all fields. This also explains why you have .86 of reward (not success rate) when the success rate of [use spinner] is .04.

**Comment by ezliu** [comment]
Thanks for noticing! We actually purposely report on partial rewards for Alaska-auto to make our results more comparable to Shi et al., 2017. Importantly, even if you consider partial rewards, getting any reward is way more sparse in Alaska-auto than for something like use spinner, because you have to fill out all of the fields. The probability of randomly getting reward in Alaska-auto is less than 10^-20!

Our model performs poorly on use-spinner for a sillier reason. Our model only considers on leaf elements in the web page, and it's not possible to change the value of the spinner by only clicking on these leaf elements.
